/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.36).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.*;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-01-08T23:33:38.407Z[GMT]")
@Validated
public interface ArtistsApi {

    @CrossOrigin(origins = "http://localhost:3000")
    @Operation(summary = "Retrieve a list of artists", description = "Retrieves a list of all artists", tags={ "Artists" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ArtistSummary.class)))),
        
        @ApiResponse(responseCode = "204", description = "List empty; no results"),
        
        @ApiResponse(responseCode = "400", description = "Request was not well-formed, see error details", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse400.class))),
        
        @ApiResponse(responseCode = "5XX", description = "Server error; no results, try again later") })
    @RequestMapping(value = "/artists",
        produces = { "application/json", "application/csv" }, 
        method = RequestMethod.GET)
    ResponseEntity<String> artistsGet(@NotNull  @Max(100) @Parameter(in = ParameterIn.QUERY, description = "Limit the number of returned items" ,required=true,schema=@Schema(allowableValues={  }, maximum="100"
, defaultValue="50")) @Valid @RequestParam(value = "limit", required = true, defaultValue="50") Integer limit, @Parameter(in = ParameterIn.QUERY, description = "The name of the Artist" ,schema=@Schema()) @Valid @RequestParam(value = "artistsName", required = false) String artistsName, @Parameter(in = ParameterIn.QUERY, description = "id of an artist" ,schema=@Schema()) @Valid @RequestParam(value = "id", required = false) String id);

    @CrossOrigin(origins = "http://localhost:3000")
    @Operation(summary = "Artists by popularity", description = "Retrieves artists by popularity for a given year", tags={ "Artists" })
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ArtistSummary.class)))),

            @ApiResponse(responseCode = "204", description = "List empty; no results"),

            @ApiResponse(responseCode = "400", description = "Request was not well-formed, see error details", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse400.class))),

            @ApiResponse(responseCode = "5XX", description = "Server error; no results, try again later") })
    @RequestMapping(value = "/artists/popularity",
            produces = { "application/json", "application/csv" },
            method = RequestMethod.GET)
    ResponseEntity<String> artistsGetByPopularity(@NotNull  @Max(100) @Parameter(in = ParameterIn.QUERY, description = "Limit the number of returned items" ,required=true,schema=@Schema(allowableValues={  }, maximum="100"
            , defaultValue="50")) @Valid @RequestParam(value = "limit", required = true, defaultValue="50") Integer limit, @Parameter(in = ParameterIn.QUERY, description = "Artists by song release year" ,schema=@Schema()) @Valid @RequestParam(value = "year", required = true) String year);

    @CrossOrigin(origins = "http://localhost:3000")
    @Operation(summary = "Deletes artists songs by name or id", description = "Deletes artists songs by name or id", tags={ "Artists" })
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ArtistSummary.class)))),

            @ApiResponse(responseCode = "204", description = "List empty; no results"),

            @ApiResponse(responseCode = "400", description = "Request was not well-formed, see error details", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse400.class))),

            @ApiResponse(responseCode = "5XX", description = "Server error; no results, try again later") })
    @RequestMapping(value = "/artists",
            produces = { "application/json", "application/csv" },
            method = RequestMethod.DELETE)
    ResponseEntity<Void> artistsDelete(@Parameter(in = ParameterIn.QUERY, description = "The name of the Artist" ,schema=@Schema()) @Valid @RequestParam(value = "artistsName", required = false) String artistsName, @Parameter(in = ParameterIn.QUERY, description = "id of an artist" ,schema=@Schema()) @Valid @RequestParam(value = "id", required = false) String id);

    /*@CrossOrigin(origins = "http://localhost:3000")
    @Operation(summary = "Delete an artist", description = "Deletes the artist with the given id", tags={ "Artists" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Artist deleted successfully"),
        
        @ApiResponse(responseCode = "400", description = "Request was not well-formed, see error details", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse400.class))),
        
        @ApiResponse(responseCode = "404", description = "Resource not found"),
        
        @ApiResponse(responseCode = "5XX", description = "Server error; no results, try again later") })
    @RequestMapping(value = "/artists/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> artistsIdDelete(@Parameter(in = ParameterIn.PATH, description = "The ID of the artist", required=true, schema=@Schema()) @PathVariable("id") String id);
*/
    @CrossOrigin(origins = "http://localhost:3000")
    @Operation(summary = "Retrieve a selected artist", description = "Retrieves the artist with the given id", tags={ "Artists" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ArtistSummary.class))),
        
        @ApiResponse(responseCode = "400", description = "Request was not well-formed, see error details", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse400.class))),
        
        @ApiResponse(responseCode = "404", description = "Resource not found"),
        
        @ApiResponse(responseCode = "5XX", description = "Server error; no results, try again later") })
    @RequestMapping(value = "/artists/{id}",
        produces = { "application/json", "application/csv" }, 
        method = RequestMethod.GET)
    ResponseEntity<String> artistsIdGet(@Parameter(in = ParameterIn.PATH, description = "The ID of the artist", required=true, schema=@Schema()) @PathVariable("id") String id);

    @CrossOrigin(origins = "http://localhost:3000")
    @Operation(summary = "Update an artist", description = "Updates the artist with the given id", tags={ "Artists" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Artist updated, returns the new state", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Artist.class))),
        
        @ApiResponse(responseCode = "400", description = "Request was not well-formed, see error details", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse400.class))),
        
        @ApiResponse(responseCode = "404", description = "Resource not found"),
        
        @ApiResponse(responseCode = "5XX", description = "Server error; no results, try again later") })
    @RequestMapping(value = "/artists/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json", "application/csv" }, 
        method = RequestMethod.POST)
    ResponseEntity<Artist> artistsIdPost(@Parameter(in = ParameterIn.PATH, description = "The ID of the artist", required=true, schema=@Schema()) @PathVariable("id") String id, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Artist body);

    @CrossOrigin(origins = "http://localhost:3000")
    @Operation(summary = "Retrieve a list of songs performed by a selected artist", description = "Retrieves all songs performed by the artist with the given id, possibly filtered by the requested criteria", tags={ "Artists" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ArtistSummary.class)))),
        
        @ApiResponse(responseCode = "204", description = "List empty; no results"),
        
        @ApiResponse(responseCode = "400", description = "Request was not well-formed, see error details", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse400.class))),
        
        @ApiResponse(responseCode = "404", description = "Resource not found"),
        
        @ApiResponse(responseCode = "5XX", description = "Server error; no results, try again later") })
    @RequestMapping(value = "/artists/{id}/songs",
        produces = { "application/json", "application/csv" }, 
        method = RequestMethod.GET)
    ResponseEntity<String> artistsIdSongsGet(@Parameter(in = ParameterIn.PATH, description = "The ID of the artist", required=true, schema=@Schema()) @PathVariable("id") String id, @Parameter(in = ParameterIn.QUERY, description = "" ,schema=@Schema()) @Valid @RequestParam(value = "order-by", required = false) SongFilterKeys orderBy, @Parameter(in = ParameterIn.QUERY, description = "The directorion to order the indicated column" ,schema=@Schema(allowableValues={ "asc", "desc" }
, defaultValue="desc")) @Valid @RequestParam(value = "order-dir", required = false, defaultValue="desc") String orderDir);

    @CrossOrigin(origins = "http://localhost:3000")
    @Operation(summary = "Create a new artist", description = "Creates a new artist with the given information", tags={ "Artists" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Artist successfully added", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Integer.class))),
        
        @ApiResponse(responseCode = "400", description = "Request was not well-formed, see error details", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InlineResponse400.class))),
        
        @ApiResponse(responseCode = "409", description = "Artist with the same name and songs already exists"),
        
        @ApiResponse(responseCode = "5XX", description = "Server error; no results, try again later") })
    @RequestMapping(value = "/artists",
        produces = { "application/json" }, 
        consumes = { "application/json", "application/csv" }, 
        method = RequestMethod.POST)
    ResponseEntity<Integer> artistsPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Artist body);

}

